apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Homelab Root CA
  secretName: homelab-root-ca
  duration: 87600h
  renewBefore: 8760h
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: homelab-selfsigned
    kind: Issuer
    group: cert-manager.io
