apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-home-arpa
  namespace: nextcloud
spec:
  secretName: nextcloud-home-arpa-tls
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - nextcloud.home.arpa
  usages:
    - server auth
    - digital signature
    - key encipherment
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
    group: cert-manager.io
