apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nextcloud-longhorn
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2replicas
  resources:
    requests:
      storage: 100Gi
