apiVersion: v1
kind: Pod
metadata:
  name: nextcloud-volume-migration
  namespace: nextcloud
spec:
  restartPolicy: Never
  containers:
    - name: migration
      image: alpine:3.22
      command: ["sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: source
          mountPath: /source
          readOnly: true
        - name: destination
          mountPath: /destination
  volumes:
    - name: source
      persistentVolumeClaim:
        claimName: nextcloud-nextcloud
    - name: destination
      persistentVolumeClaim:
        claimName: nextcloud-nextcloud-longhorn
